name: CI

on:
  push:
    branches: [ "main" ]

env:
 airflow: test
 common: 0
 mlflow: 0
 modeloperator: 0
 streamlit_app: 0
 ts_classifier: 0

jobs:
  conntroller:
    runs-on: ubuntu-latest
    outputs:
      airflow: ${{ steps.init.outputs.airflow }}
      common: ${{ steps.init.outputs.common }}
      mlflow: ${{ steps.init.outputs.mlflow }}
      modeloperator: ${{ steps.init.outputs.modeloperator }}
      streamlit_app: ${{ steps.init.outputs.streamlit_app }}
      ts_classifier:  ${{ steps.init.outputs.ts_classifier }}
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
      - name: List all changed files
        id: init
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "$file was changed"
              
              if [[ $file == "airflow/"* ]]; then
                  echo "::set-output name=airflow::1"
              fi

              if [[ $file == "common/"* ]]; then
                  echo "::set-output name=common::1"
              fi

              if [[ $file == "mlflow/"* ]]; then
                  echo "::set-output name=mlflow::1"
              fi

              if [[ $file == "modeloperator/"* ]]; then
                  echo "::set-output name=modeloperator::1"
              fi

              if [[ $file == "streamlit_app/"* ]]; then
              echo "::set-output name=streamlit_app::1"
              fi

              if [[ $file == "ts_classifier/"* ]]; then
              echo "::set-output name=ts_classifier::1"
              fi
          done

      - name: Print environment variables
        run: |
          echo "Airflow: ${{ needs.conntroller.outputs.airflow }}"
          echo "Common: ${{ needs.conntroller.outputs.common }}"
          echo "MLflow: ${{ needs.conntroller.outputs.mlflow }}"
          echo "ModelOperator: ${{ needs.conntroller.outputs.modeloperator }}"
          echo "Streamlit App: ${{ needs.conntroller.outputs.streamlit_app }}"
          echo "TS Classifier: ${{ needs.conntroller.outputs.ts_classifier }}"