name: CI

on:
  push:
    branches: [ "main" ]

env:
  airflow: 0
  common: 0
  mlflow: 0
  modeloperator: 0
  streamlit_app: 0
  ts_classifier: 0

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      airflow: ${{ steps.set-env.outputs.airflow }}
      common: ${{ steps.set-env.outputs.common }}
      mlflow: ${{ steps.set-env.outputs.mlflow }}
      modeloperator: ${{ steps.set-env.outputs.modeloperator }}
      streamlit_app: ${{ steps.set-env.outputs.streamlit_app }}
      ts_classifier: ${{ steps.set-env.outputs.ts_classifier }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40

      - name: Set environment variables
        id: set-env
        run: |
          echo "airflow=$([[ ${{ steps.changed-files.outputs.all_changed_files }} == *'airflow/'* ]] && echo 1 || echo 0)" >> $GITHUB_OUTPUT
          echo "common=$([[ ${{ steps.changed-files.outputs.all_changed_files }} == *'common/'* ]] && echo 1 || echo 0)" >> $GITHUB_OUTPUT
          echo "mlflow=$([[ ${{ steps.changed-files.outputs.all_changed_files }} == *'mlflow/'* ]] && echo 1 || echo 0)" >> $GITHUB_OUTPUT
          echo "modeloperator=$([[ ${{ steps.changed-files.outputs.all_changed_files }} == *'modeloperator/'* ]] && echo 1 || echo 0)" >> $GITHUB_OUTPUT
          echo "streamlit_app=$([[ ${{ steps.changed-files.outputs.all_changed_files }} == *'streamlit_app/'* ]] && echo 1 || echo 0)" >> $GITHUB_OUTPUT
          echo "ts_classifier=$([[ ${{ steps.changed-files.outputs.all_changed_files }} == *'ts_classifier/'* ]] && echo 1 || echo 0)" >> $GITHUB_OUTPUT

  airflow:
    needs: set-env
    if: needs.set-env.outputs.airflow == '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Airflow version
        run: |
          echo "Airflow version:"
          cat airflow/version.txt

  common:
    needs: set-env
    if: needs.set-env.outputs.common == '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Common version
        run: |
          echo "Common version:"
          cat common/version.txt

  mlflow:
    needs: set-env
    if: needs.set-env.outputs.mlflow == '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Mlflow version
        run: |
          echo "Mlflow version:"
          cat mlflow/version.txt

  modeloperator:
    needs: set-env
    if: needs.set-env.outputs.modeloperator == '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print ModelOperator version
        run: |
          echo "ModelOperator version:"
          cat modeloperator/version.txt

  streamlit_app:
    needs: set-env
    if: needs.set-env.outputs.streamlit_app == '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Streamlit_app version
        run: |
          echo "Streamlit_app version:"
          cat streamlit_app/version.txt

  ts_classifier:
    needs: set-env
    if: needs.set-env.outputs.ts_classifier == '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Ts_classifier version
        run: |
          echo "Ts_classifier version:"
          cat ts_classifier/version.txt