name: CI

on:
  push:
    branches: [ "main" ]

env:
  airflow: 0
  common: 0
  mlflow: 0
  modeloperator: 0
  streamlit_app: 0
  ts_classifier: 0

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      airflow: ${{ steps.init.outputs.airflow }}
      common: ${{ steps.init.outputs.common }}
      mlflow: ${{ steps.init.outputs.mlflow }}
      modeloperator: ${{ steps.init.outputs.modeloperator }}
      streamlit_app: ${{ steps.init.outputs.streamlit_app }}
      ts_classifier: ${{ steps.init.outputs.ts_classifier }}

    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
      - name: List all changed files
        id: init
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "$file was changed"
              
              if [[ $file == "airflow/"* ]]; then
                  echo "::set-output name=airflow::1"
              fi

              if [[ $file == "common/"* ]]; then
                  echo "::set-output name=common::1"
              fi

              if [[ $file == "mlflow/"* ]]; then
                  echo "::set-output name=mlflow::1"
              fi

              if [[ $file == "modeloperator/"* ]]; then
                  echo "::set-output name=modeloperator::1"
              fi

              if [[ $file == "streamlit_app/"* ]]; then
                  echo "::set-output name=streamlit_app::1"
              fi

              if [[ $file == "ts_classifier/"* ]]; then
                  echo "::set-output name=ts_classifier::1"
              fi
          done
          
  airflow:
    needs: set-env
    if: needs.set-env.outputs.airflow == '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Airflow version
        run: |
          echo "Airflow version:"
          cat airflow/version.txt

  common:
    needs: set-env
    if: needs.set-env.outputs.common == '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Common version
        run: |
          echo "Common version:"
          cat common/version.txt

  mlflow:
    needs: set-env
    if: needs.set-env.outputs.mlflow == '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Mlflow version
        run: |
          echo "Mlflow version:"
          cat mlflow/version.txt

  modeloperator:
    needs: set-env
    if: needs.set-env.outputs.modeloperator == '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print ModelOperator version
        run: |
          echo "ModelOperator version:"
          cat modeloperator/version.txt

  streamlit_app:
    needs: set-env
    if: needs.set-env.outputs.streamlit_app == '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Streamlit_app version
        run: |
          echo "Streamlit_app version:"
          cat streamlit_app/version.txt

  ts_classifier:
    needs: set-env
    if: needs.set-env.outputs.ts_classifier == '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Ts_classifier version
        run: |
          echo "Ts_classifier version:"
          cat ts_classifier/version.txt